PP - EXÉRCICIO 3 - KENNEDY MOTA - 81613747 - CCP3AN-MCA2

1 - Faça um Programa que peça dois números e imprima o maior deles.

In [1]:
num1 = input ("Digite um número: ")
num2 = input("Digite um número: ")

if num1 > num2:
    print ("O maior número é o: ", num1)
elif num1 == num2:
    print("Os números são iguais!")
else:
    print("O maior número é o: ", num2)

Digite um número: 20
Digite um número: 10
O maior número é o:  20


2 - Faça um Programa que verifique se uma letra digitada é vogal ou consoante. 

In [2]:
letra = input("Digite uma letra.")
print ("A letra digitada foi: ",letra)
if (letra == 'a' or letra == 'A' or letra == 'e' or letra == 'E' or letra == 'i' or letra == 'I'
    or letra == 'o' or letra == 'O' or letra == 'u' or letra == 'U'):
    print ("A letra digita é uma Vogal!")
else:
    print("A letra digitada é uma Consoante!")

Digite uma letra.b
A letra digitada foi:  b
A letra digitada é uma Consoante!


3 - Faça um programa para a leitura de duas notas parciais de um aluno. O programa deve calcular a média alcançada por aluno e apresentar: - A mensagem "Aprovado", se a média alcançada for maior ou igual a sete; - A mensagem "Reprovado", se a média for menor do que sete; - A mensagem "Aprovado com Distinção", se a média for igual a dez.

In [3]:
nota1 = int(input("Digite a primeira nota: "))
nota2 = int(input("Digite a segunda nota: "))

media = (nota1 + nota2)/2

print (media)
if(media >= 7 and media != 10):
    print("Aprovado!")
elif(media < 7):
        print ("Reprovado!")
elif(media == 10):
            print ("Aprovado com Distinção.")

Digite a primeira nota: 8
Digite a segunda nota: 4
6.0
Reprovado!


4 - Faça um Programa que leia três números e mostre-os em ordem decrescente. 

In [4]:
num1 = int(input("Digite o primeiro número: "))
num2 = int(input("Digite o segundo número:  "))
num3 = int(input("Digite o terceiro número: "))

if(num1 > num2 and num1 > num3 and num2 > num3 ):
    print("",num1,"\n",num2,"\n",num3,"\n")
elif(num1 > num2 and num1> num3 and num3 > num2):
    print("",num1,"\n",num3,"\n",num2)
elif(num2 > num1 and num2 > num3 and num1>num3):
    print("",num2,"\n",num1,"\n",num3)
elif(num2 > num1 and num2 > num3 and num3>num1):
    print("",num2,"\n",num3,"\n",num1)
elif(num3 > num1 and num3 > num2 and num1>num2):
    print("",num3,"\n",num1,"\n",num2)
elif(num3 > num1 and num3 > num2 and num2>num1):
    print("",num3,"\n",num2,"\n",num1)

Digite o primeiro número: 10
Digite o segundo número:  20
Digite o terceiro número: 30
 30 
 20 
 10


5 - As Organizações Tabajara resolveram dar um aumento de salário aos seus colaboradores e lhe contrataram para desenvolver o programa que calculará os reajustes. Faça um programa que recebe o salário de um colaborador e o reajuste segundo o seguinte critério, baseado no salário atual: - salários até R$ 280,00 (incluindo) : aumento de 20% - salários entre R$ 280,00 e R$ 700,00 : aumento de 15% - salários entre R$ 700,00 e R$ 1500,00 : aumento de 10% - salários de R$ 1500,00 em diante : aumento de 5% Após o aumento ser realizado, informe na tela: - o salário antes do reajuste; - o percentual de aumento aplicado; - o valor do aumento; - o novo salário, após o aumento. 

In [5]:
salario = int (input("Digite o salario do colaborador: "))
salario_reajustado = 0

if(salario <= 280):
    salario_reajustado = salario + (salario*0.20)
    print("Salario antes do reajuste:",salario)
    print('Percentual de aumento aplicado: 20%')
    print("Valor do aumento: ",salario_reajustado - salario)
    print("Novo Salario",salario_reajustado)
elif(salario > 280 and salario <=  699):
    salario_reajustado = salario + (salario*0.15)
    print("Salario antes do reajuste:",salario)
    print('Percentual de aumento aplicado: 15%')
    print("Valor do aumento: ",salario_reajustado - salario)
    print("Novo Salario",salario_reajustado)
elif(salario >= 700 and salario <= 1499):
    salario_reajustado = salario + (salario*0.10)
    print("Salario antes do reajuste:",salario)
    print('Percentual de aumento aplicado: 10%')
    print("Valor do aumento: ",salario_reajustado - salario)
    print("Novo Salario",salario_reajustado)
elif(salario >= 1500):
    salario_reajustado = salario + (salario*0.05)
    print("Salario antes do reajuste:",salario)
    print('Percentual de aumento aplicado: 5%')
    print("Valor do aumento: ",salario_reajustado - salario)
    print("Novo Salario",salario_reajustado)

Digite o salario do colaborador: 1500
Salario antes do reajuste: 1500
Percentual de aumento aplicado: 5%
Valor do aumento:  75.0
Novo Salario 1575.0


6 - Faça um Programa que leia um número e exiba o dia correspondente da semana. (1-Domingo, 2- Segunda, etc.), se digitar outro valor deve aparecer valor inválido. 

In [6]:
numero = int(input("Digite um número, referente ao dia da semana, (entre 1 e 7): "))

if (numero == 1):
    print("Domingo")
elif(numero == 2):
        print("Segunda-Feira")
elif(numero == 3):
            print("Terça-Feira")
elif(numero == 4):
                print("Quarta-Feira")
elif(numero == 5):
                    print("Quinta-Feira")
elif(numero == 6):
                        print("Sexta-Feira")
elif(numero == 7):
                            print("Sabado")
else:
                                print("Valor inválido")

Digite um número, referente ao dia da semana, (entre 1 e 7): 5
Quinta-Feira


7- Faça um programa que lê as duas notas parciais obtidas por um aluno numa disciplina ao longo de um semestre, e calcule a sua média. A atribuição de conceitos obedece à tabela abaixo:   Média de Aproveitamento  Conceito   Entre 9.0 e 10.0        A   Entre 7.5 e 9.0         B   Entre 6.0 e 7.5         C   Entre 4.0 e 6.0         D   Entre 4.0 e zero        E O algoritmo deve mostrar na tela as notas, a média, o conceito correspondente e a mensagem “APROVADO” se o conceito for A, B ou C ou “REPROVADO” se o conceito for D ou E. 

In [7]:
nota1 = int(input("Digite a primeira nota: "))
nota2 = int(input("Digite a segunda nota:  "))

media = (nota1 + nota2)/2

if(media >= 9 and media <= 10):
    print("Notas: nota 1: ",nota1,"- Nota2: ",nota2)
    print("Média do Aluno: ",media)
    print("Conceito: A")
    print("Aprovado")
elif(media>= 7.5 and media <9):
    print("Notas: nota 1: ",nota1,"- Nota2: ",nota2)
    print("Média do Aluno: ",media)
    print("Conceito: B")
    print("Aprovado")
elif(media>= 6 and media < 7.5):
    print("Notas: nota 1: ",nota1,"- Nota2: ",nota2)
    print("Média do Aluno: ",media)
    print("Conceito: C")
    print("Aprovado")
elif(media>= 4 and media <6):
    print("Notas: nota 1: ",nota1,"- Nota2: ",nota2)
    print("Média do Aluno: ",media)
    print("Conceito: D")
    print("REPROVADO!")
elif(media< 4):
    print("Notas: nota 1: ",nota1,"- Nota2: ",nota2)
    print("Média do Aluno: ",media)
    print("Conceito: E")
    print("REPROVADO!")


Digite a primeira nota: 5
Digite a segunda nota:  8
Notas: nota 1:  5 - Nota2:  8
Média do Aluno:  6.5
Conceito: C
Aprovado


8- Faça um Programa que peça os 3 lados de um triângulo. O programa deverá
informar se os valores podem ser um triângulo. Indique, caso os lados formem um
triângulo, se o mesmo é: equilátero, isósceles ou escaleno.
Dicas:
- Três lados formam um triângulo quando a soma de quaisquer dois lados for maior
que o terceiro;
- Triângulo Equilátero: três lados iguais;
- Triângulo Isósceles: quaisquer dois lados iguais;
- Triângulo Escaleno: três lados diferentes;

In [8]:
ladoa = int(input("Digite o lado A do triangulo: "))
ladob = int(input("Digite o lado B do triangulo: "))
ladoc = int(input("Digite o lado C do triangulo: "))

triangulo = False;

if((ladoa + ladob) > ladoc):
    triangulo = True
    
    if(ladoa == ladob and ladoa == ladoc):
        print("O triangulo é Equilátero")
    elif(ladoa == ladob or ladoa == ladoc or ladob == ladoc):
        print("O triangulo é Isósceles")
    elif(ladoa != ladob and ladoa != ladoc and ladob != ladoc):
        print("O triangulo é Escaleno")
else:
    print("Não é um triangulo!")

Digite o lado A do triangulo: 20
Digite o lado B do triangulo: 10
Digite o lado C do triangulo: 10
O triangulo é Isósceles


9 - Faça um programa que calcule as raízes de uma equação do segundo grau, na
forma ax2 + bx + c. O programa deverá pedir os valores de a, b e c e fazer as
consistências, informando ao usuário nas seguintes situações:
- Se o usuário informar o valor de A igual a zero, a equação não é do segundo grau e
o programa não deve fazer pedir os demais valores, sendo encerrado;
- Se o delta calculado for negativo, a equação não possui raizes reais. Informe ao
usuário e encerre o programa;
- Se o delta calculado for igual a zero a equação possui apenas uma raiz real;
informe-a ao usuário;
- Se o delta for positivo, a equação possui duas raiz reais; informe-as ao usuário;

In [9]:
import sys

a = int(input("Digite o valor de A: "))
while(a == 0):
        print("O valor de A deve ser maior que ZERO!")
        break;
else:
    b = int(input("Digite o valor de B: "))
    c = int(input("Digite o valor de C: "))

    delta = (b*b) - (4*a)*c

    if(delta < 0):
        print("O delta é negativo, a equação não possui raizes reais.")
    elif(delta == 0):
        print("A equação possui apenas 1 raiz real.")
    elif(delta > 0):
        print("A equação possui duas raizes reais.")




Digite o valor de A: 10
Digite o valor de B: 20
Digite o valor de C: 30
O delta é negativo, a equação não possui raizes reais.


10 - Faça um Programa para um caixa eletrônico. O programa deverá perguntar ao
usuário a valor do saque e depois informar quantas notas de cada valor serão
fornecidas. As notas disponíveis serão as de 1, 5, 10, 50 e 100 reais. O valor mínimo é
de 10 reais e o máximo de 600 reais. O programa não deve se preocupar com a
quantidade de notas existentes na máquina.
- Exemplo 1: Para sacar a quantia de 256 reais, o programa fornece duas notas de
100, uma nota de 50, uma nota de 5 e uma nota de 1;
- Exemplo 2: Para sacar a quantia de 399 reais, o programa fornece três notas de
100, uma nota de 50, quatro notas de 10, uma nota de 5 e quatro notas de 1.

In [5]:
saque = int(input("Digite o valor do saque: "))

if 10 <= saque <= 600:
    notas_cem = saque 
    saque = saque % 100

    notas_cinquenta = saque 
    saque = saque % 50

    notas_dez = saque
    saque = saque % 10

    notas_cinco = saque 
    saque = saque % 5

    notas_um = saque 

    if notas_cem > 0:
        print(notas_cem, "notas de R$ 100")
    if notas_cinquenta > 0:
        print(notas_cinquenta, "notas de R$ 50")
    if notas_dez > 0:
        print(notas_dez, "notas de R$ 10")
    if notas_cinco > 0:
        print(notas_cinco, "notas de R$ 5")
    if notas_um > 0:
        print(notas_um, "notas de R$ 1")
              
else:
    print("Nao é possivel fazer o saque")

Digite o valor do saque: 50
50 notas de R$ 100
50 notas de R$ 50


11 - Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As
perguntas são:
"Telefonou para a vítima?"
"Esteve no local do crime?"
"Mora perto da vítima?"
"Devia para a vítima?"
"Já trabalhou com a vítima?"
O programa deve no final emitir uma classificação sobre a participação da pessoa no
crime. Se a pessoa responder positivamente a 2 questões ela deve ser classificada
como "Suspeita", entre 3 e 4 como "Cúmplice" e 5 como "Assassino". Caso contrário,
ele será classificado como "Inocente".

In [10]:
qtde = 0    
p1 = int(input("Telefonou para a vítima? ""\nOBS: Responda com 1 para SIM e 2 para NÃO: "))
if(p1 == 1):
    qtde +=1
    print(qtde)
p2 = int(input("Esteve no local do crime? ""\nOBS: Responda com 1 para SIM e 2 para NÃO:: "))
if(p2 == 1):
    qtde +=1
    print(qtde)
p3 = int(input("Mora perto da vítima? ""\nOBS: Responda com 1 para SIM e 2 para NÃO: "))
if(p3 == 1):
    qtde +=1
    print(qtde)
p4 = int(input("Devia para a vítima? ""\nOBS: Responda com 1 para SIM e 2 para NÃO: "))

if(p4 == 1):
    qtde +=1
    print(qtde)
p5 = int(input("Ja trabalhou com a vítima? ""\nOBS: Responda com 1 para SIM e 2 para NÃO: "))
if(p5 == 1):
    qtde +=1
    print(qtde)
    
if(qtde == 2):
    print("SUSPEITA!")
elif(qtde >=3 and qtde <=4):
    print("CÚMPLICE")
elif(qtde==5):
    print("ASSASSINO!")
elif(qtde <=1):
    print("Esta pessoa é: Inocente :)")

Telefonou para a vítima? 
OBS: Responda com 1 para SIM e 2 para NÃO: 1
1
Esteve no local do crime? 
OBS: Responda com 1 para SIM e 2 para NÃO:: 2
Mora perto da vítima? 
OBS: Responda com 1 para SIM e 2 para NÃO: 1
2
Devia para a vítima? 
OBS: Responda com 1 para SIM e 2 para NÃO: 2
Ja trabalhou com a vítima? 
OBS: Responda com 1 para SIM e 2 para NÃO: 1
3
CÚMPLICE


12 - Uma fruteira está vendendo frutas com a seguinte tabela de preços:
Até 5 Kg Acima de 5 Kg
Morango R$ 2,50 por Kg R$ 2,20 por Kg
Maçã R$ 1,80 por Kg R$ 1,50 por Kg
Se o cliente comprar mais de 8 Kg em frutas ou o valor total da compra ultrapassar
R$ 25,00, receberá ainda um desconto de 10% sobre este total. Escreva um
algoritmo para ler a quantidade (em Kg) de morangos e a quantidade (em Kg) de
maças adquiridas e escreva o valor a ser pago pelo cliente.

In [11]:
qtde_morango = int(input("Digite a quantidade de Morangos: "))
qtde_macas = int(input("Digite a quantidade de Maçãs: "))

qtde_total = qtde_morango + qtde_macas
valor_pagar = (qtde_morango * 2.50) + (qtde_macas * 1.80)

if(qtde_total > 8 or valor_pagar > 25):
    valor_desconto = (valor_pagar * 10)/100
    print("Valor do desconto: ",valor_desconto)
    print("Valor a pagar: ",valor_pagar - valor_desconto)
else:
    print("Valor a pagar: ",valor_pagar)

Digite a quantidade de Morangos: 50
Digite a quantidade de Maçãs: 12
Valor do desconto:  14.66
Valor a pagar:  131.94


13 - Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.

In [12]:
while True:
    nota = int(input('Informe uma nota entre 0 e 10... '))
    if nota >= 0 and nota <= 10:
        break
    else:
        print(f'A nota informada é invalida. insira um valor entre 0 e 10...')
        continue 

Informe uma nota entre 0 e 10... 4


14 - Faça um programa que leia 5 números e informe o maior número.

In [13]:
cont = 0
lista = []
while cont < 5:
    lista.append( float(input('Número: ')))
    cont +=1
else:
    print('O maior valor informado é: %.0f' %max(lista))
    

Número: 10
Número: 5
Número: 78
Número: 12
Número: 35
O maior valor informado é: 78


15 - Faça um programa que leia 5 números e informe a soma e a média dos números. 

In [14]:
cont = 0
soma = 0
while cont < 5:
    n = float(input('Nº: '))
    cont +=1
    soma= soma + n
else:
    media = soma / cont
    print('A soma dos numeros é: %.0f'%soma)
    print('A média dos numeros é: %.1f'%media)


Nº: 1
Nº: 521
Nº: 54
Nº: 65
Nº: 65
A soma dos numeros é: 706
A média dos numeros é: 141.2


16 - Faça um programa que imprima na tela apenas os números ímpares entre 1 e 50.

In [15]:
#fazendo uma lista de 0 a 50
lista = list(range(1,51))

In [16]:
#imprimindo na tela
print(lista)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [17]:
#imprimindo apenas os números ímpares
for num in lista:
    if num%2 != 0:
        print(num)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49


17 - Desenvolva um gerador de tabuada, capaz de gerar a tabuada de qualquer
número inteiro entre 1 a 10. O usuário deve informar de qual numero ele deseja ver
a tabuada. A saída deve ser conforme o exemplo abaixo:
Tabuada de 5:
5 X 1 = 5
5 X 2 = 10
...
5 X 10 = 50


In [18]:
a = int(input('Qual tabuada deseja ver? '))
b = int(input('ate qual valor? '))

for res in range(0, b+1):
    print(f'{a:2} X {res:2} = ', a * res)

Qual tabuada deseja ver? 5
ate qual valor? 10
 5 X  0 =  0
 5 X  1 =  5
 5 X  2 =  10
 5 X  3 =  15
 5 X  4 =  20
 5 X  5 =  25
 5 X  6 =  30
 5 X  7 =  35
 5 X  8 =  40
 5 X  9 =  45
 5 X 10 =  50


18 - A série de Fibonacci é formada pela seqüência 1,1,2,3,5,8,13,21,34,55,... Faça um programa capaz degerar a série até o n−ésimo termo.

In [19]:
list = []

def fib(n):
    a = 0
    b = 1;
    while (b < n):
        c = a
        a = b
        b = a + c
        print (a)

In [20]:
fib(20)

1
1
2
3
5
8
13


In [21]:
fib(20000)

1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765
10946
17711


19 - Faça um programa que calcule o fatorial de um número inteiro fornecido pelo usuário. Ex.: 5!=5.4.3.2.1=120

In [22]:
i = 1  # contador
n_fat = 1 
n = int(input('Numero a ser Fatorado: '))
# calcule n!
while i <= n:
    n_fat = n_fat * i 
    i = i + 1    
else:  
    print("%d! = %d" %(n, n_fat))   

Numero a ser Fatorado: 5
5! = 120


20 - O Sr. Manoel Joaquim possui uma grande loja de artigos de R$ 1,99, com cerca de 10 caixas. Para agilizar o cálculo de quanto cada cliente deve pagar ele desenvolveu um tabela que contém o número de itens que o cliente comprou e ao lado o valor da conta. Desta forma a atendente do caixa precisa apenas contar quantos itens o cliente está levando e olhar na tabela de preços. Você foi contratado para desenvolver o programa que monta esta tabela de preços, que conterá os preços de 1 até 50 produtos.

In [23]:
print('Loja Quase Dois - Tabela de preços')
for i in range(1,51):
     print ('%15d - R$ %.2f' % (i, i * 1.99))

Loja Quase Dois - Tabela de preços
              1 - R$ 1.99
              2 - R$ 3.98
              3 - R$ 5.97
              4 - R$ 7.96
              5 - R$ 9.95
              6 - R$ 11.94
              7 - R$ 13.93
              8 - R$ 15.92
              9 - R$ 17.91
             10 - R$ 19.90
             11 - R$ 21.89
             12 - R$ 23.88
             13 - R$ 25.87
             14 - R$ 27.86
             15 - R$ 29.85
             16 - R$ 31.84
             17 - R$ 33.83
             18 - R$ 35.82
             19 - R$ 37.81
             20 - R$ 39.80
             21 - R$ 41.79
             22 - R$ 43.78
             23 - R$ 45.77
             24 - R$ 47.76
             25 - R$ 49.75
             26 - R$ 51.74
             27 - R$ 53.73
             28 - R$ 55.72
             29 - R$ 57.71
             30 - R$ 59.70
             31 - R$ 61.69
             32 - R$ 63.68
             33 - R$ 65.67
             34 - R$ 67.66
             35 - R$ 69.65
             36 - R$ 71.6

21 - O Sr. Manoel Joaquim acaba de adquirir uma panificadora e pretende implantar
a metodologia da tabelinha, que já é um sucesso na sua loja de 1,99. Você foi
contratado para desenvolver o programa que monta a tabela de preços de pães, de
1 até 50 pães, a partir do preço do pão informado pelo usuário, conforme o exemplo
abaixo:
Preço do pão: R$ 0.18
Panificadora Pão de Ontem - Tabela de preços
1 - R$ 0.18
2 - R$ 0.36
...
50 - R$ 9.00

In [24]:
valor = float(input('Qua o preço do pão? '))
for res in range(1, 51):
    print(f'{res:2} - R${valor * res:4.2f}')

Qua o preço do pão? 2
 1 - R$2.00
 2 - R$4.00
 3 - R$6.00
 4 - R$8.00
 5 - R$10.00
 6 - R$12.00
 7 - R$14.00
 8 - R$16.00
 9 - R$18.00
10 - R$20.00
11 - R$22.00
12 - R$24.00
13 - R$26.00
14 - R$28.00
15 - R$30.00
16 - R$32.00
17 - R$34.00
18 - R$36.00
19 - R$38.00
20 - R$40.00
21 - R$42.00
22 - R$44.00
23 - R$46.00
24 - R$48.00
25 - R$50.00
26 - R$52.00
27 - R$54.00
28 - R$56.00
29 - R$58.00
30 - R$60.00
31 - R$62.00
32 - R$64.00
33 - R$66.00
34 - R$68.00
35 - R$70.00
36 - R$72.00
37 - R$74.00
38 - R$76.00
39 - R$78.00
40 - R$80.00
41 - R$82.00
42 - R$84.00
43 - R$86.00
44 - R$88.00
45 - R$90.00
46 - R$92.00
47 - R$94.00
48 - R$96.00
49 - R$98.00
50 - R$100.00


22 - O Sr. Manoel Joaquim expandiu seus negócios para além dos negócios de 1,99 e agora possui uma loja de conveniências. Faça um programa que implemente uma caixa registradora rudimentar. O programa deverá receber um número desconhecido de valores referentes aos preços das mercadorias. Um valor zero deve ser informado pelo operador para indicar o final dacompra. O programa deve então mostrar o total da compra e perguntar o valor em dinheiro que o cliente forneceu, para então calcular e mostrar o valor do troco. Após esta operação, o programa deverá voltar ao ponto inicial, para registrar a próxima compra.A saída deve ser conforme o exemplo abaixo:Lojas Tabajara Produto 1: R$ 2.20Produto 2: R 5.80Produto 3: R 0Total: R 9.00Dinheiro: R 20.00 Troco: R 11.00

In [27]:
def controladorCaixa():
    listaValores = []
    valorProduto = ""
    contProduto = 0

    while valorProduto != 0:
        contProduto += 1
        valorProduto = float(input(f'Produto {contProduto}: R$ '))
        listaValores.append(valorProduto)
    else:
        contProduto = 0
        contador = 0
        total = sum(listaValores)
        print('Lojas Tabajara')
        for i in listaValores:
            contProduto +=1
            print(f'Produto {contProduto}: R$ {listaValores[contador]:{10}.{6}}')
            contador +=1
        print(f'Total: R$ {total:{10}.{6}}')
        valorPagamento = float(input(f'Qual o valor que o cliente forneceu: R$ '))
        print(f'Dinheiro: R$ {valorPagamento}')
        troco = valorPagamento - total
        print(f'Troco: R$ {troco}')
        print('...')
        controladorCaixa()

In [ ]:
controladorCaixa()

Produto 1: R$ 50
Produto 2: R$ 20
Produto 3: R$ 30
Produto 4: R$ 0
Lojas Tabajara
Produto 1: R$       50.0
Produto 2: R$       20.0
Produto 3: R$       30.0
Produto 4: R$        0.0
Total: R$      100.0
Qual o valor que o cliente forneceu: R$ 250
Dinheiro: R$ 250.0
Troco: R$ 150.0
...
Produto 1: R$ 500
Produto 2: R$ 300
Produto 3: R$ 200
Produto 4: R$ 0
Lojas Tabajara
Produto 1: R$      500.0
Produto 2: R$      300.0
Produto 3: R$      200.0
Produto 4: R$        0.0
Total: R$     1000.0
Qual o valor que o cliente forneceu: R$ 2500
Dinheiro: R$ 2500.0
Troco: R$ 1500.0
...


23 - Foi feita uma estatística em cinco cidades brasileiras para coletar dados sobre acidentes de trânsito. Foram obtidos os seguintes dados: 
-Código da cidade; 
-Número de veículos de passeio (em 1999); 
-Número de acidentes de trânsito com vítimas (em 1999). 
Deseja-se saber: 
-Qual o maior e menor índice de acidentes de transito e a que cidade pertence; 
-Qual a média de veículos nas cinco cidades juntas; 
-Qual a média de acidentes de trânsito nas cidades com menos de 2.000 veículos de passeio. 

In [1]:
tamanho = 5
cod_cidade =  [0] * tamanho
n_acidentes = [0] * tamanho
n_veiculos =  [0] * tamanho

for i in range(tamanho):
    cod_cidade[1] = int(input('Codigo da cidade: '))
    n_veiculos[i] = int(input('Numero de veiculos de passeio: '))
    n_acidentes[i]= int(input('Numero de acidentes: ')) 
    
def SomaAcidentes(listaAcidentes):
    totalAcidentes=0
    for numeroLista1 in listaAcidentes:
        totalAcidentes += numeroLista1
    return totalAcidentes
    
def SomaVeiculos(listaVeiculos):
    totalVeiculos=0
    for numeroLista2 in listaVeiculos:
        totalVeiculos += numeroLista2
    return totalVeiculos

def MediaVeiculos(listaVeiculos):
    return (SomaVeiculos(n_veiculos) / len(listaVeiculos))

def MediaAcidentes(listaAcidentes):
    return (SomaAcidentes(n_acidentes) / len(listaAcidentes))

print ('\nMaior indice de acidentes: ',max(n_acidentes))
print ('Menor indice de acidentes: ',min(n_acidentes))
print ('Media de veículos: ', MediaVeiculos(n_veiculos))
print ('Média de acidentes de transito nas cidades com menos de 2 Mil veículos: ', MediaAcidentes(n_acidentes))




Codigo da cidade: 5
Numero de veiculos de passeio: 50
Numero de acidentes: 12
Codigo da cidade: 6
Numero de veiculos de passeio: 48
Numero de acidentes: 7
Codigo da cidade: 7
Numero de veiculos de passeio: 26
Numero de acidentes: 0
Codigo da cidade: 8
Numero de veiculos de passeio: 68
Numero de acidentes: 5
Codigo da cidade: 9
Numero de veiculos de passeio: 25
Numero de acidentes: 1

Maior indice de acidentes:  12
Menor indice de acidentes:  0
Media de veículos:  43.4
Média de acidentes de transito nas cidades com menos de 2 Mil veículos:  5.0


24 - Faça um programa que receba o valor de uma dívida e mostre uma tabela com os seguintes dados: valor da dívida, valor dos juros, quantidade de parcelas e valor da parcela. Os juros e a quantidade de parcelas seguem a tabela abaixo: Quantidade de Parcelas  % de Juros sobre o valor inicial da dívida 

In [2]:

divida = float(input('Insira o valor da dívida: '))

print('Valor da Dívida | Valor dos Juros | Qtd de Parcelas | Valor da Parcela')

juros = 0

for qtdParcelas in [1, 3, 6, 9, 12]:
    valorJuros = (divida * (juros / 100.0))
    valorDivida = divida + valorJuros
    valorParcela = valorDivida / qtdParcelas
    print ('R$ %.2f\t| R$ %.2f\t  |% i \t\t    | R$ %.2f' %(valorDivida, valorJuros, qtdParcelas, valorParcela))
    
    if (qtdParcelas == 1):
        juros = 10.0
    else:
        juros += 5.0

Insira o valor da dívida: 150
Valor da Dívida | Valor dos Juros | Qtd de Parcelas | Valor da Parcela
R$ 150.00	| R$ 0.00	  | 1 		    | R$ 150.00
R$ 165.00	| R$ 15.00	  | 3 		    | R$ 55.00
R$ 172.50	| R$ 22.50	  | 6 		    | R$ 28.75
R$ 180.00	| R$ 30.00	  | 9 		    | R$ 20.00
R$ 187.50	| R$ 37.50	  | 12 		    | R$ 15.62


25 - Faça um programa que mostre os n termos da Série a seguir:S = 1/1 + 2/3 + 3/5 + 4/7 + 5/9 + ... + n/m. Imprima no final a soma da série.

In [3]:
termo = int(input('Insira a quantidade de termos desejada: '))

s = float(0)
m = 1
for n in range(1, termo + 1):
    s += n / m
    m += 2
    
print ('Soma da série: %.2f' % s)

Insira a quantidade de termos desejada: 3
Soma da série: 2.27


PP - EXÉRCICIO 3 - KENNEDY MOTA - 81613747 - CCP3AN-MCA2